<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edp.Workflow.Application\Edp.Workflow.Application.csproj" />
    <ProjectReference Include="..\Edp.Workflow.Domain\Edp.Workflow.Domain.csproj" />
  </ItemGroup>

</Project>
