import { NavLink } from 'react-router';

const cards = [
  { label: 'Documents', value: 'Open work queue', to: '/documents', tone: 'bg-teal-50 text-teal-800' },
  { label: 'Templates', value: 'Manage library', to: '/templates', tone: 'bg-indigo-50 text-indigo-800' },
  { label: 'Approvals', value: 'Review assigned work', to: '/approvals', tone: 'bg-amber-50 text-amber-800' },
  { label: 'Audit', value: 'Trace activity', to: '/audit', tone: 'bg-slate-100 text-slate-800' }
];

export function DashboardPage() {
  return <section className="space-y-8"><div><p className="text-sm font-medium text-teal-700">Workspace overview</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Good work starts here.</h2><p className="mt-2 max-w-2xl text-slate-600">Create from a trusted template, move documents through approval, and keep every decision traceable.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => <NavLink key={card.to} to={card.to} className={`rounded-xl p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${card.tone}`}><p className="text-sm font-medium opacity-75">{card.label}</p><p className="mt-6 text-lg font-semibold">{card.value}</p><span className="mt-3 inline-block text-sm underline underline-offset-4">Open →</span></NavLink>)}</div><div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-semibold">Recommended first steps</h3><ol className="mt-4 space-y-4 text-sm text-slate-600"><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-slate-900 text-xs font-semibold text-white">1</span><span><strong className="text-slate-900">Activate a template.</strong> Upload a DOCX and validate its placeholders.</span></li><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-slate-900 text-xs font-semibold text-white">2</span><span><strong className="text-slate-900">Generate a document.</strong> Provide typed business data and request DOCX/PDF output.</span></li><li className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-slate-900 text-xs font-semibold text-white">3</span><span><strong className="text-slate-900">Review the trail.</strong> Approvals and audit events remain tied to the organization context.</span></li></ol></div><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-semibold">System status</h3><p className="mt-2 text-sm text-slate-600">Live service status is surfaced by the Gateway. If a service is unavailable, affected pages retain a retry action and do not discard your form data.</p><NavLink to="/documents" className="mt-5 inline-flex rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Open documents</NavLink></div></div></section>;
}
