FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ../src/Services/Notification/Edp.Notification.Api/Edp.Notification.Api.csproj ./
RUN dotnet restore "Edp.Notification.Api.csproj"
COPY ../src/Services/Notification/Edp.Notification.Api/. ./
RUN dotnet publish "Edp.Notification.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Edp.Notification.Api.dll"]
