FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ../src/Services/Template/Edp.Template.Api/Edp.Template.Api.csproj ./
RUN dotnet restore "Edp.Template.Api.csproj"
COPY ../src/Services/Template/Edp.Template.Api/. ./
RUN dotnet publish "Edp.Template.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Edp.Template.Api.dll"]
