FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ../src/Gateway/Edp.Gateway/Edp.Gateway.csproj ./
RUN dotnet restore "Edp.Gateway.csproj"
COPY ../src/Gateway/Edp.Gateway/. ./
RUN dotnet publish "Edp.Gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Edp.Gateway.dll"]
