import { useEffect, useState } from 'react';
import { ApiError } from '../../services/apiClient';
import { items, platformApi, type SigningRequest } from '../../services/platformApi';

export function SigningPage() {
  const [requests, setRequests] = useState<SigningRequest[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = () => platformApi.signing.list().then(result => setRequests(items(result))).catch(e => setError(e instanceof ApiError ? e.message : 'Signing requests could not be loaded.'));
  useEffect(() => { void load(); }, []);
  const action = async (id: string, kind: 'activate' | 'cancel') => { setBusy(id); setError(''); try { await platformApi.signing[kind](id); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : `Request could not be ${kind}d.`); } finally { setBusy(''); } };
  return <section className="space-y-6"><div><p className="text-sm font-medium text-teal-700">Execution</p><h2 className="text-3xl font-semibold">Signing</h2><p className="mt-1 text-sm text-slate-600">Track signing requests and signer progress.</p></div>{error && <p role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Request</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Progress</th><th className="px-5 py-3">Created</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{requests.length === 0 ? <tr><td colSpan={5} className="px-5 py-12 text-center text-slate-500">No signing requests available.</td></tr> : requests.map(r => <tr key={r.signingRequestId}><td className="px-5 py-4 font-semibold">{r.title}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{r.status}</span></td><td className="px-5 py-4">{r.signedCount} / {r.signerCount}</td><td className="px-5 py-4 text-slate-500">{new Date(r.createdAt).toLocaleDateString()}</td><td className="px-5 py-4">{r.status.toLowerCase() === 'draft' && <button disabled={busy === r.signingRequestId} className="mr-2 rounded bg-slate-900 px-2 py-1 text-xs font-semibold text-white" onClick={() => void action(r.signingRequestId, 'activate')}>Activate</button>}{!['completed', 'cancelled', 'expired'].includes(r.status.toLowerCase()) && <button disabled={busy === r.signingRequestId} className="rounded border border-red-300 px-2 py-1 text-xs font-semibold text-red-700" onClick={() => void action(r.signingRequestId, 'cancel')}>Cancel</button>}</td></tr>)}</tbody></table></div></section>;
}
